config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 2, maximum: 200 }
  validates :description, presence: true, length: { minimum: 10, maximum: 3000 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 80 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action!"
      redirect_to login_path
    end  
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :reqiure_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was succesfully saved."
      redirect_to @article 
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was succesfully updated."
      redirect_to @article
    else
      render 'edit'
    end    
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def reqiure_same_user
    if current_user != @article.user && current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect Credentials!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}!"
      redirect_to @user
    else
      render "new"
    end    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account Updated!"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Successfully deleted your account and all your articles."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 96 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="article col-8 justify-content-md-center">
    <div class="card text-center mb-4 shadow-sm">
      <div class="card-header">
        by <%= link_to article.user.username, user_path(article.user) %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary btn-sm" %>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-secondary btn-sm" %>
          <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-outline-danger btn-sm" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small class="m-0">Created at: <%= time_ago_in_words(article.created_at) %> ago</small>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: "3" %>
  </div>

  <%= f.submit "Save", class: "btn btn-primary mb-2" %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Edit article</h1>
  <%= render 'form' %>
  <%= link_to  "Back to Articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div id="all-articles">
  <div class="container">
    <h2 class="text-center mt-4">Listing All Articles</h2>
    <% if logged_in? %>
    <%= link_to 'Add New Article', new_article_path, class: 'btn btn-primary mb-4' %>
    <% end %>
    
    <%= render 'article' %>
    
    <div class="flickr_pagination mb-4">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Create new article</h1>
  <%= render 'form' %>
  <div class="text-center mt-4">
    <%= link_to 'Cancel and Return to Articles List', articles_path, class: 'text-center' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4"><%= @article.title %></h1>
    <p><strong>Created at: </strong><%= time_ago_in_words(@article.created_at) %> ago, <strong>Author: </strong> <%= @article.user.username %></p>
  </div>
</div>

<div class="container">
  <p><%= @article.description %></p>

  <%= link_to 'Back to Articles', articles_path, class: 'btn btn-outline-primary' %>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: 'btn btn-outline-danger' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Alpha Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Blog", articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav mb-0">
      <% if logged_in? %>
      <li class="nav-item ml-3">
        <%= link_to current_user.username, user_path(current_user), class: "text-white" %>
      </li>
      <li class="nav-item ml-3">
        <%= link_to  "Log Out", logout_path, class: "btn btn-outline-primary btn-sm", method: :delete %>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to  "Log In", login_path, class: "btn btn-outline-primary btn-sm" %>
        </li>
        <li class="nav-item ml-3">
          <%= link_to  "Sign Up", signup_path, class: "btn btn-primary btn-sm" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |name, msg| %>
  <div class="alert <% if name == 'alert' %>alert-danger<% else %>alert-success<% end %> alert-dismissible fade show m-4" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notifications' %>
    <div id="page-content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h5>Following errors prevented <%= obj.class.name.downcase %> from being saved</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary mb-2") %>
<% end %>

app/views/users/_user.html.erb
<% @users.each do |user| %>
  <div class="user col-8 justify-content-md-center">
    <div class="card text-center mb-4 shadow-sm">
      <div class="card-header">
        by <%= user.username %>
      </div>
      <div class="card-body">
        <%= link_to gravatar_for(user, size: 128), user_path(user) %>
        <h5 class="card-title"><%= link_to user.username, user_path(user) %></h5>
        <p class="card-text"><%= pluralize(user.articles.count, "articles") %></p>
        <%= link_to 'Show Profile', user_path(user), class: "btn btn-outline-primary btn-sm" %>
        <% if logged_in? %>
          <% if user == current_user %>
            <%= link_to 'Edit User', edit_user_path(user), class: "btn btn-outline-secondary btn-sm" %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and all associated articles?" }, class: "btn btn-outline-danger btn-sm" %>
          <% end %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small class="m-0">Joined: <%= time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit User</h1>
  <%= render 'form' %>
  <div class="text-center mt-4">
    <%= link_to 'Cancel and Return to Articles List', articles_path, class: 'text-center' %>
  </div>
</div>

app/views/users/index.html.erb
<div id="all-users">
  <div class="container">
    <h2 class="text-center mt-4">Listing All Users</h2>
    <%= render 'user' %>

    <div class="flickr_pagination mb-4">
      <%= will_paginate @users, :container => false %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>
  <%= render 'form' %>
  <div class="text-center mt-4">
    <%= link_to 'Cancel and Return to Articles List', articles_path, class: 'text-center' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2><%= @user.username %><%= "(Admin)" if current_user.admin? %></h2>
  <%= gravatar_for @user %>
  <% if logged_in? && @user == current_user %>
    <%= link_to 'Edit User', edit_user_path(@user), class: "btn btn-outline-secondary btn-sm" %>
    <%= link_to 'Delete Profile', user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this your profile? All your articles will be deleted as well!" }, class: "btn btn-outline-danger btn-sm" %>
  <% end %>
  <%= render 'articles/article' %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>